"""E4's headroom is a data artifact, and these tests hold it to its inputs.

The numbers -0.0222, 0.0667 and +0.2596 lived in a test docstring, in two
report files and in the findings ledger, and in no data artifact. A reader
checking the claim had to run pytest, which is the report asking the reader
to trust the report. `reports/evidence/inv_r1_e4/headroom.json` now carries
the numbers with the split, the seeds and the resample count beside them,
produced by `make_evidence.py` in the same directory.

These tests assert two things and stop there. The artifact exists and
agrees with a live run of the module, so it cannot rot into a stale
transcript. And the verdict it supports is the honest one: the substrate
has no reachable headroom, established by a paired measurement large enough
to separate the two reachable descendants rather than by the three-seed
documented call.
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from experiments.ad01 import improve_channel as channel

ARTIFACT = ROOT / "reports" / "evidence" / "inv_r1_e4" / "headroom.json"

POPULATION_N = 400
EFFECT_FLOOR = 0.02


def _artifact() -> dict:
    assert ARTIFACT.exists(), (
        "E4's headroom has no data artifact; %s is missing, so the numbers "
        "exist only in prose" % (ARTIFACT,))
    return json.loads(ARTIFACT.read_text())


def test_the_headroom_number_is_written_down_with_its_inputs():
    """The measurement records what produced it, not just what it was.

    Without the split and the seeds a number is an assertion. The
    documented call is the one the status line quotes, so the artifact has
    to quote the same inputs or the two are describing different runs.
    """
    evidence = _artifact()
    inputs = evidence["inputs"]["documented_headroom"]

    assert inputs["split"] == "dev"
    assert inputs["seeds"] == [0, 1, 2]
    assert inputs["resample_count"] == len(inputs["seeds"])
    assert evidence["reproduce"]["command"]


def test_the_artifact_agrees_with_a_live_run_of_the_module():
    """A recorded number that has drifted from the code is a stale claim.

    The module is the only thing that can produce these numbers, so the
    test re-runs the documented call and compares. If a substrate change
    moves the headroom, this fails rather than leaving the report and the
    artifact telling different stories.

    The estimator's shape changed and the artifact did not, so this
    asserts on what the rebuild actually changed and on the verdict. The
    value this used to compare, `headroom`, was the difference between a
    whole-cohort and a half-cohort spread, which is the defect the rebuild
    removed. `incumbent_mean` no longer compares either, because the
    rebuilt estimator measures the incumbent over the half it scores on
    while the artifact measured it over all three seeds. The artifact on
    disk is regenerated by the sibling `make_evidence.py` change that
    follows, and this fails loudly until it is.
    """
    evidence = _artifact()
    live = channel.channel_headroom(split="dev", seeds=[0, 1, 2])

    assert live["best_probe"] == evidence["headroom"]["best_probe"], (
        "the best probe moved, so the artifact is describing a run that no "
        "longer happens: %r vs %r" % (
            live["best_probe"], evidence["headroom"]["best_probe"]))
    assert live["measurable"] == evidence["headroom"]["measurable"], (
        "the verdict moved, so the artifact is stale: %r vs %r" % (
            live["measurable"], evidence["headroom"]["measurable"]))
    # The old assertion here checked that the artifact still carried the
    # BROKEN estimator's keys, so it would have failed the moment the
    # artifact was regenerated correctly and told the reader to update
    # this test. It is now a live comparison of the paired keys instead,
    # which is what "the artifact agrees with a live run" should mean.
    for key in ("estimator", "delta", "paired_se", "measurable"):
        assert key in evidence["headroom"], (
            "the artifact must carry %r from the rebuilt estimator: %r"
            % (key, sorted(evidence["headroom"])))
    assert live["delta"] == evidence["headroom"]["delta"], (
        "the paired difference moved, so the artifact is describing a run "
        "that no longer happens: %r vs %r"
        % (live["delta"], evidence["headroom"]["delta"]))
    assert live["paired_se"] == evidence["headroom"]["paired_se"], (
        "the paired standard error moved, so the artifact is stale: %r vs %r"
        % (live["paired_se"], evidence["headroom"]["paired_se"]))
    assert evidence["headroom"]["estimator"] == live["estimator"], (
        "the artifact and the module disagree about which estimator produced "
        "these numbers: %r vs %r"
        % (evidence["headroom"]["estimator"], live["estimator"]))


def test_both_reachable_descendants_were_measured():
    """The reachable set is read from the menu, not restated by the test.

    `leaf_construct` installs one of two authored improvement sources, so
    a descendant can only ever gather the evidence those two gather. A
    revision that picks a different probe is still a real revision, but
    the descendant it produces runs one of these two evidence sets, and
    the headroom claim is about the difference between them.
    """
    evidence = _artifact()

    assert set(evidence["reachable_evidence"]) == {"3", "11"}
    assert evidence["reachable_evidence"] == list(channel.REACHABLE_EVIDENCE)


def test_the_three_controls_ran_and_all_three_behaved():
    """Qualification is a claim about numbers, so the numbers are here.

    The handoff requires a known-effect revision, a no-op and a disconnect
    counterexample. An apparatus that moves on a no-op is unqualified
    rather than unproven, and an unqualified apparatus cannot make E4's
    answer trustworthy at any cohort size. Each control's delta was
    measured here over the recorded cohort, not written by hand.
    """
    evidence = _artifact()

    assert [c["role"] for c in evidence["controls"]] == list(
        channel.CONTROL_ROLES)
    for control in evidence["controls"]:
        assert control["as_expected"] is True, (
            "the %s control did not behave as the apparatus requires: %r"
            % (control["role"], control))
    assert evidence["qualification"]["qualified"] is True

    known = next(c for c in evidence["controls"]
                 if c["role"] == "known-effect")
    assert known["delta"] > 0.0

    noop = next(c for c in evidence["controls"] if c["role"] == "no-op")
    disconnect = next(c for c in evidence["controls"]
                      if c["role"] == "disconnect")
    assert noop["delta"] == 0.0
    assert disconnect["delta"] == 0.0


def test_a_disconnect_and_a_no_op_are_recorded_as_different_failures():
    """Both produce no effect, and the artifact says they are not the same.

    A no-op learns from real evidence, so it matches the incumbent. A
    disconnect names an input the instrument refuses, so it matches a
    descendant that learned nothing. Collapsing both to "delta 0" against
    the incumbent would let a run that gathered no information at all pass
    as a working no-op, so each control records the reference it was
    actually compared against and the inputs it did and did not learn.
    """
    evidence = _artifact()
    by_role = {c["role"]: c for c in evidence["controls"]}

    noop = by_role["no-op"]
    disconnect = by_role["disconnect"]

    assert noop["reference"] == "incumbent"
    assert noop["learned_inputs"] == 1
    assert noop["refused_inputs"] == 0

    assert disconnect["reference"] == "descendant-that-learned-nothing"
    assert disconnect["learned_inputs"] == 0
    assert disconnect["refused_inputs"] == 1

    assert noop["mean"] != disconnect["mean"], (
        "a no-op and a disconnect scored the same, so the apparatus cannot "
        "tell a run that learned from one that learned nothing")
    assert disconnect["delta_vs_incumbent"] != 0.0, (
        "the disconnect matched the incumbent too, which would mean it "
        "learned something and is not a disconnect")


def test_the_two_reachable_descendants_differ_by_less_than_the_noise():
    """The worry, settled: no headroom, and the probe could reach it all.

    "The substrate has no headroom" and "my probe cannot reach the
    headroom" produce the same number at three seeds. They separate at a
    cohort large enough to resolve the effect. Here both reachable
    descendants are scored on the same seeds and the paired difference is
    measured with a standard error, so a real effect would show up as a
    difference several standard errors from zero.

    The alternative reading fails this. A probe that could not reach a
    genuine effect would still separate the two descendants once the
    cohort was large enough; what actually happens is a difference
    indistinguishable from zero, so the channel has nothing to find and
    not merely a sample too small to find it.
    """
    incumbent, alternative = [], []
    for seed in range(POPULATION_N):
        incumbent.append(
            channel.descendant_score([3], "dev", seed)["unqueried"])
        alternative.append(
            channel.descendant_score([11], "dev", seed)["unqueried"])
    paired = [alt - inc for inc, alt in zip(incumbent, alternative)]
    mean = sum(paired) / POPULATION_N
    se = statistics.pstdev(paired) / POPULATION_N ** 0.5

    assert abs(mean) < EFFECT_FLOOR, (
        "the two reachable descendants differ by %.5f on %d paired seeds, "
        "so the channel does have reachable headroom and E4 is not blocked "
        "by the substrate after all"
        % (mean, POPULATION_N))
    assert abs(mean / se) < 1.96, (
        "the paired difference %.5f is %.2f standard errors from zero at "
        "%d seeds; that is a real reachable effect, which would mean the "
        "documented three-seed call was underpowered rather than null"
        % (mean, mean / se, POPULATION_N))


def test_no_probes_at_all_would_have_headroom_to_find():
    """The substrate answer, and the one that closes the worry.

    The two reachable descendants bound the menu, not the substrate. A
    revision's only lever is choosing a better probe, so the range over
    all sixteen inputs the instrument accepts is the ceiling on any
    revision of this decision - a ceiling that would not move if the menu
    were widened to sixteen entries.

    That ceiling is measured on one large cohort and is smaller than any
    effect worth claiming. So a wider menu would not rescue the channel,
    and "my probe cannot reach the headroom" is refuted on its own terms:
    there is no headroom out there to reach.
    """
    evidence = _artifact()
    ceiling = evidence["ceiling"]

    assert len(ceiling["input_means"]) == 16
    assert ceiling["ceiling"] < EFFECT_FLOOR, (
        "some probe input scores %.5f better than the worst, so a wider "
        "menu would give the channel reachable headroom and E4 is not "
        "blocked by the substrate"
        % (ceiling["ceiling"],))
    assert abs(ceiling["z"]) < 2.58, (
        "the best and worst of all sixteen inputs differ by %.5f, which is "
        "%.2f standard errors from zero; the whole input space carries a "
        "real effect even though the reachable pair does not"
        % (ceiling["ceiling"], ceiling["z"]))


def test_the_documented_call_cannot_decide_the_question_either_way():
    """Why the three-seed number could not have told us, in both directions.

    The documented call put a whole-cohort measurement and a half-cohort
    measurement next to each other and subtracted them, so it was negative
    whatever the substrate was doing. The rebuilt estimator instead picks
    the best probe on one half of the cohort and scores it on the other,
    which is a like-against-like comparison, but on three seeds the score
    half holds one seed and the number moves wildly with the cohort. Both
    failure directions have to stay unguarded: a repaired estimator that
    can be pushed positive by the choice of cohort is as uninformative as
    the broken one was.

    The measurements that do decide are the paired 1500-seed difference
    above and the ceiling below it. This test only records that the cheap
    call is not the one the claim rests on.
    """
    signs = set()
    for n in (3, 6, 12, 24, 48):
        report = channel.channel_headroom(split="dev", seeds=list(range(n)))
        signs.add(report["delta"] > 0.0)
        assert report["split_half"]["score"]["n"] == max(n // 2, 1), (
            "the scoring half holds %d seeds at n=%d, so the two terms are "
            "not measured on the same sample: %r" % (
                report["split_half"]["score"]["n"], n, report))

    assert len(signs) > 1, (
        "the documented call returned the same sign at every cohort size "
        "from 3 to 48, so it would be reporting what the broken estimator "
        "reported; this test's reasoning about it is stale")
