"""A representation manifest cannot be regenerated byte-for-byte on Windows.

`experiments/representation/splits.py` writes
`str(target.relative_to(root))` into `manifest.json`, and
`experiments/representation/acquire/contexts.py` returns
`str(path.relative_to(fixtures_root))` as the `path` of every task it
bundles. Both render with the host separator, so a rebuild on Windows names
`controls\\ctrl-gr-bipartite.json` where the committed manifest names
`controls/ctrl-gr-bipartite.json`. The per-file digests are still correct,
which is what makes this quiet: the manifest that describes them is simply a
different byte string on each operating system.

Both are pinned. `splits.verify_manifest` re-derives from the paths it reads,
and `experiments/representation/experiment/freeze.py` raises
`committed source_context.json drifted from its generator` when the rebuilt
context does not digest to the committed bytes. A freeze is the identity of a
study, and an identity that only reproduces on one platform is not an
identity.

Every assertion names a literal path or a literal committed digest, so each
one fails if either builder goes back to the host-native form.
"""

import hashlib
import json
import subprocess
import tempfile
from pathlib import Path

from experiments.representation import splits
from experiments.representation.acquire import contexts

REPO = Path(__file__).parent.parent
FIXTURES = REPO / "experiments" / "representation" / "fixtures"
ACQUIRE = REPO / "experiments" / "representation" / "acquire"
FIRST_FIXTURE = "controls/ctrl-gr-bipartite.json"
SOURCE_FIRST = "software/development/sw-dev-00.json"
TRANSFER_FIRST = "graphs/development/gr-dev-00.json"


def _sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _canonical(doc: dict) -> bytes:
    return (json.dumps(doc, sort_keys=True, indent=2) + "\n").encode()


def _committed_bytes(rel: str) -> bytes:
    """The bytes Git holds for a path, free of this host's line endings."""
    return subprocess.run(["git", "-C", str(REPO), "show", f"HEAD:{rel}"],
                          capture_output=True, check=True).stdout


def test_a_built_fixture_manifest_names_its_files_with_forward_slashes():
    with tempfile.TemporaryDirectory() as root:
        built = splits.write_fixtures(Path(root))
    assert built["files"][0]["path"] == FIRST_FIXTURE


def test_a_built_fixture_manifest_is_byte_identical_to_the_committed_one():
    """The freeze is regenerable. This is the property a digest cannot show.

    Every `digest` field matches on both hosts, so a check over digests alone
    passes while the manifest as a whole differs. The comparison is over the
    exact bytes that get committed.
    """
    with tempfile.TemporaryDirectory() as root:
        splits.write_fixtures(Path(root))
        rebuilt_raw = (Path(root) / "manifest.json").read_bytes()
        rebuilt_pin = (Path(root) / "manifest.sha256").read_text().strip()
    committed_raw = (FIXTURES / "manifest.json").read_bytes()
    committed_pin = (FIXTURES / "manifest.sha256").read_text().strip()
    assert committed_pin == rebuilt_pin, "manifest.sha256 would not be reproducible"
    assert committed_raw == rebuilt_raw, "manifest.json bytes differ from committed"


def test_a_built_fixture_manifest_verifies_against_its_own_pins():
    with tempfile.TemporaryDirectory() as root:
        splits.write_fixtures(Path(root))
        assert splits.verify_manifest(Path(root)) == []


def test_a_built_context_names_its_tasks_with_forward_slashes():
    source = contexts.build_source_context(FIXTURES)
    assert source["tasks"][0]["path"] == SOURCE_FIRST
    transfer = contexts.build_transfer_context(FIXTURES)
    assert transfer["tasks"][0]["path"] == TRANSFER_FIRST


def test_a_built_context_digests_to_the_committed_bytes():
    """What `freeze.py:145` compares, driven directly.

    This is the assertion that makes the defect loud. The committed contexts
    hold forward slashes, so a backslash in any task path changes the
    document digest and `build_panel_manifest` refuses to certify the freeze.

    Compared against the committed blob, not the working-tree file.
    `experiments/representation/acquire/**` carries no `eol=lf` rule, so with
    `core.autocrlf=true` the checkout holds CRLF and the comparison would
    report a line-ending difference that has nothing to do with the path. That
    is a separate, reported defect. The bytes Git holds are what the freeze
    is defined over.
    """
    for name, builder in (("source_context.json", contexts.build_source_context),
                          ("transfer_context.json", contexts.build_transfer_context)):
        committed = _committed_bytes("experiments/representation/acquire/" + name)
        assert _sha256(committed) == _sha256(_canonical(builder(FIXTURES))), \
            f"{name} drifted from its generator on this host"


def test_the_committed_context_task_paths_are_forward_slash():
    for name in ("source_context.json", "transfer_context.json"):
        doc = json.loads((ACQUIRE / name).read_bytes())
        assert all("\\" not in task["path"] for task in doc["tasks"]), name


def test_a_context_task_path_locates_the_fixture_it_names():
    """The string is not a label; `run.py:817` reads through it.

    `(ROOT / entry["path"]).read_bytes()` treats it as a path. A backslash is
    a legal filename character on Windows, so the read succeeds locally and
    resolves to nothing at all on the host that consumes the context.
    """
    source = contexts.build_source_context(FIXTURES)
    for task in source["tasks"]:
        assert (FIXTURES / task["path"]).is_file(), task["path"]
        assert _sha256((FIXTURES / task["path"]).read_bytes()) == task["digest"]
