ALTER TABLE agenda_traj_state
    ADD COLUMN IF NOT EXISTS ticks JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS idle INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS feasible_wait INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS liabilities JSONB NOT NULL DEFAULT '[]';
